export const DESCRIPCION_INDICADOR: Record<string, string> = {
  LIQ_01: 'Capacidad para cubrir pasivos corrientes',
  LIQ_02: 'Liquidez sin depender del inventario',
  SOL_01: 'Participación de acreedores en los activos',
  SOL_02: 'Deuda frente a recursos propios',
  SOL_03: 'Cobertura del activo fijo con patrimonio',
  SOL_04: 'Proporción corriente de la deuda',
  SOL_05: 'Proporción no corriente de la deuda',
  SOL_06: 'Capacidad para cubrir gastos financieros',
  SOL_07: 'Activos por unidad de patrimonio',
  GES_01: 'Veces que rota la cartera',
  GES_02: 'Ventas generadas por activo fijo',
  GES_03: 'Eficiencia de los activos',
  GES_04: 'Días promedio de cobranza',
  GES_06: 'Peso de gastos operativos',
  GES_07: 'Peso de gastos financieros',
  REN_01: 'Capacidad de activos para producir utilidad',
  REN_02: 'Rentabilidad antes de gastos operativos',
  REN_03: 'Rentabilidad de la operación',
  REN_04: 'Utilidad neta por venta',
  REN_05: 'Rentabilidad operativa de recursos propios',
  REN_07: 'Rentabilidad operativa de activos',
  REN_08: 'Rentabilidad neta del patrimonio',
  REN_09: 'Rentabilidad neta de activos',
}
