export type ParameterGroupId = 'normative' | 'indicators' | 'simulator' | 'catalogs'
export type ParameterEntityId = 'norms'|'obligations'|'obligationRules'|'normativeParams'|'financialConcepts'|'clusterConcepts'|'derivedMagnitudes'|'indicators'|'clusterIndicators'|'benchmarks'|'scenarios'|'scenarioVariables'|'scenarioResults'|'industryClusters'|'economicActivities'|'corporateStructures'|'taxpayerTypes'|'professionalSpecialties'
export type FieldType = 'text'|'textarea'|'number'|'date'|'url'|'checkbox'|'select'|'json'
export type CellType = 'text'|'status'|'boolean'|'date'|'number'|'relation'|'json'
export type FormFieldSchema={key:string;label:string;type?:FieldType;required?:boolean;full?:boolean;options?:string[];optionsFrom?:ParameterEntityId|'modules';labelKey?:string;nullable?:boolean;defaultValue?:unknown}
export type ColumnSchema={key:string;label:string;type?:CellType;relationTo?:ParameterEntityId|'modules';labelKey?:string;secondaryKey?:string}
export type ParameterEntitySchema={id:ParameterEntityId;title:string;singular:string;description:string;searchKeys:string[];columns:ColumnSchema[];fields:FormFieldSchema[]}
export type ParameterGroupSchema={id:ParameterGroupId;label:string;description:string;entities:ParameterEntitySchema[]}
const schema=(id:ParameterEntityId, title:string, fields:FormFieldSchema[]):ParameterEntitySchema=>({id,title,singular:title.slice(0,-1),description:`Catálogo de ${title.toLocaleLowerCase('es')}.`,searchKeys:['codigo','nombre','descripcion'],columns:fields.slice(0,6).map((field)=>({key:field.key,label:field.label,type:field.key==='activo'?'status':field.type==='checkbox'?'boolean':field.type==='date'?'date':field.type==='number'?'number':field.type==='json'?'json':field.optionsFrom?'relation':'text',relationTo:field.optionsFrom,labelKey:field.labelKey,secondaryKey:field.key==='nombre'?'descripcion':undefined})),fields})
const f=(key:string,label=key,type:FieldType='text',required=false,extra:Partial<FormFieldSchema>={})=>({key,label,type,required,...extra})
const bool=(key:string,label=key,defaultValue=false)=>f(key,label,'checkbox',false,{defaultValue})
const rel=(key:string,label:string,optionsFrom:ParameterEntityId,required=false,nullable=false)=>f(key,label,'select',required,{optionsFrom,labelKey:'nombre',nullable})
const norms=schema('norms','Normas',[f('nombre','Nombre','text',true),f('tipo','Tipo','text',true),f('institucion','Institución','text',true),f('numero','Número'),f('url_fuente','URL de fuente','url'),f('fecha_publicacion','Fecha publicación','date'),f('fecha_vigencia','Fecha vigencia','date'),f('estado','Estado','select',false,{options:['VIGENTE','DEROGADA','BORRADOR'],defaultValue:'VIGENTE'})])
const obligations=schema('obligations','Obligaciones',[f('codigo','Código','text',true),f('nombre','Nombre','text',true),f('descripcion','Descripción','textarea'),f('categoria','Categoría','select',false,{options:['TRIBUTARIA','LABORAL','SOCIETARIA','MUNICIPAL'],defaultValue:'TRIBUTARIA'}),f('institucion','Institución'),f('periodicidad','Periodicidad','select',false,{options:['MENSUAL','BIMESTRAL','TRIMESTRAL','SEMESTRAL','ANUAL','EVENTUAL']}),bool('usa_noveno_digito'),bool('permite_monto_estimado'),bool('activo','Activo',true)])
const obligationRules=schema('obligationRules','Reglas de obligación',[rel('obligacion_id','Obligación','obligations',true),rel('norma_legal_id','Norma legal','norms',false,true),f('nombre','Nombre','text',true),f('descripcion','Descripción','textarea'),rel('tipo_contribuyente_id','Tipo contribuyente','taxpayerTypes',false,true),rel('estructura_societaria_id','Estructura','corporateStructures',false,true),rel('actividad_economica_id','Actividad','economicActivities',false,true),rel('cluster_id','Cluster','industryClusters',false,true),f('tamano_empresa','Tamaño','select'),bool('requiere_contabilidad'),bool('requiere_declaracion_impuestos'),f('noveno_digito_desde','Noveno desde','number'),f('noveno_digito_hasta','Noveno hasta','number'),f('formula_fecha','Fórmula fecha','textarea'),bool('formula_fecha_validada'),f('formula_monto','Fórmula monto','textarea'),bool('formula_monto_validada'),f('prioridad','Prioridad','number',false,{defaultValue:1}),f('vigente_desde','Vigente desde','date'),f('vigente_hasta','Vigente hasta','date',false,{nullable:true}),bool('activo','Activo',true)])
const normativeParams=schema('normativeParams','Parámetros normativos',[rel('norma_legal_id','Norma','norms',false,true),f('codigo','Código','text',true),f('nombre','Nombre','text',true),f('categoria','Categoría','select',true,{options:['TRIBUTARIO','LABORAL','SOCIETARIO','MUNICIPAL']}),f('descripcion','Descripción','textarea'),f('tipo_valor','Tipo','select'),f('valor','Valor','json'),f('unidad','Unidad'),f('fuente','Fuente'),f('vigente_desde','Vigente desde','date'),f('vigente_hasta','Vigente hasta','date'),bool('activo','Activo',true)])
const financialConcepts=schema('financialConcepts','Conceptos financieros',[f('codigo','Código','text',true),f('nombre','Nombre','text',true),f('bloque','Bloque','text',true),f('descripcion','Descripción','textarea'),f('tipo_dato','Tipo dato','select'),f('unidad','Unidad'),bool('es_universal'),bool('obligatorio'),f('regla_validacion','Regla validación','json'),f('orden_visualizacion','Orden','number'),bool('activo','Activo',true)])
const clusterConcepts=schema('clusterConcepts','Conceptos cluster',[rel('cluster_id','Cluster','industryClusters',true),rel('concepto_financiero_id','Concepto','financialConcepts',true),bool('obligatorio')])
const derivedMagnitudes=schema('derivedMagnitudes','Magnitudes derivadas',[rel('cluster_id','Cluster','industryClusters',false,true),f('codigo','Código','text',true),f('nombre','Nombre','text',true),f('expresion','Expresión','textarea',true),f('version','Versión','text',true),bool('formula_validada'),f('descripcion','Descripción','textarea'),bool('activo','Activo',true)])
const indicators=schema('indicators','Indicadores',[f('codigo','Código','text',true),f('factor','Factor','select',true,{options:['LIQUIDEZ','SOLVENCIA','GESTION','RENTABILIDAD']}),f('nombre','Nombre','text',true),f('descripcion','Descripción','textarea'),f('formula','Fórmula','textarea',true),bool('formula_validada'),f('interpretacion','Interpretación','textarea'),f('unidad','Unidad'),f('fuente','Fuente'),f('fase','Fase'),f('version_formula','Versión fórmula'),f('peso_salud_financiera','Peso','number'),bool('activo','Activo',true)])
const clusterIndicators=schema('clusterIndicators','Indicadores cluster',[rel('cluster_id','Cluster','industryClusters',true),rel('indicador_id','Indicador','indicators',true),bool('es_principal'),bool('activo','Activo',true)])
const benchmarks=schema('benchmarks','Benchmarks',[rel('indicador_id','Indicador','indicators',true),rel('cluster_id','Cluster','industryClusters',true),f('banda_tamano','Banda','text',true),f('periodo_referencia','Periodo','date',true),f('fuente','Fuente'),f('percentil_10','P10','number'),f('percentil_25','P25','number'),f('percentil_50','P50','number'),f('percentil_75','P75','number'),f('percentil_90','P90','number'),f('cantidad_muestra','Muestra','number'),f('vigente_desde','Desde','date'),f('vigente_hasta','Hasta','date'),bool('activo','Activo',true)])
const scenarios=schema('scenarios','Escenarios',[f('codigo','Código','text',true),f('nombre','Nombre','text',true),f('categoria','Categoría','select',true,{options:['FINANCIERO','TRIBUTARIO','LABORAL','SOCIETARIO']}),f('descripcion','Descripción','textarea'),bool('activo','Activo',true)])
const scenarioVariables=schema('scenarioVariables','Variables de escenario',[rel('escenario_id','Escenario','scenarios',true),f('codigo','Código','text',true),f('nombre','Nombre','text',true),f('descripcion','Descripción','textarea'),f('tipo_dato','Tipo','select'),f('unidad','Unidad'),f('valor_minimo','Mínimo','number'),f('valor_maximo','Máximo','number'),bool('obligatoria','Requerida',true),f('orden_visualizacion','Orden','number'),bool('activo','Activo',true)])
const scenarioResults=schema('scenarioResults','Resultados de escenario',[rel('escenario_id','Escenario','scenarios',true),f('codigo','Código','text',true),f('nombre','Nombre','text',true),f('descripcion','Descripción','textarea'),f('formula','Fórmula','textarea'),bool('formula_validada'),f('tipo_resultado','Tipo','select'),f('unidad','Unidad'),f('orden_visualizacion','Orden','number'),bool('activo','Activo',true)])
const industryClusters=schema('industryClusters','Clusters',[f('codigo','Código','text',true),f('nombre','Nombre','text',true),f('descripcion','Descripción','textarea'),bool('activo','Activo',true)])
const economicActivities=schema('economicActivities','Actividades económicas',[rel('cluster_predeterminado_id','Cluster','industryClusters',false,true),f('codigo_ciiu','Código CIIU','text',true),f('nombre','Nombre','text',true),f('descripcion','Descripción','textarea'),f('sector','Sector'),f('categoria','Categoría'),bool('activo','Activo',true)])
const corporateStructures=schema('corporateStructures','Estructuras',[f('codigo','Código','text',true),f('nombre','Nombre','text',true),f('descripcion','Descripción','textarea'),f('tipo_persona','Tipo persona','select'),bool('activo','Activo',true)])
const taxpayerTypes=schema('taxpayerTypes','Tipos contribuyente',[f('codigo','Código','text',true),f('nombre','Nombre','text',true),f('descripcion','Descripción','textarea'),f('tipo_persona','Tipo persona','select'),f('regimen_tributario','Régimen'),bool('obligado_contabilidad'),bool('contribuyente_especial'),bool('agente_retencion'),bool('gran_contribuyente'),bool('declara_iva'),f('periodicidad_iva','Periodicidad IVA','select'),bool('declara_renta'),bool('emite_factura'),bool('activo','Activo',true)])
const professionalSpecialties=schema('professionalSpecialties','Especialidades',[f('codigo','Código','text',true),f('nombre','Nombre','text',true),f('categoria','Categoría'),f('descripcion','Descripción','textarea'),bool('activo','Activo',true)])
export const parameterGroups:ParameterGroupSchema[]=[{id:'normative',label:'Tributarios',description:'Normativa tributaria.',entities:[obligations,obligationRules,norms,normativeParams]},{id:'indicators',label:'Indicadores',description:'Motor de indicadores.',entities:[financialConcepts,clusterConcepts,derivedMagnitudes,indicators,clusterIndicators,benchmarks]},{id:'simulator',label:'Simulador',description:'Escenarios.',entities:[scenarios,scenarioVariables,scenarioResults]},{id:'catalogs',label:'Otros catálogos',description:'Catálogos base.',entities:[industryClusters,economicActivities,corporateStructures,taxpayerTypes,professionalSpecialties]}]
